const allProducts = {
    'preventa': [
        { id: 1, name: 'BOYNEXTDOOR - The Action (Standard ver.)', price: 'S/ 70.00', img: 'images/album/boynextdoor-theaction.png' },
        { id: 2, name: 'BOYNEXTDOOR - The Action (Frame ver.)', price: 'S/ 120.00', img: 'images/album/boynextdoor-theaction-frame.png'},
        { id: 3, name: 'ONEWE - Maze (Ad Astra ver.)', price: 'S/ 65.00', img: 'images/album/onewe-maze-adastra.jpg' },
        { id: 4, name: 'ONEWE - Maze (Maze ver.)', price: 'S/ 65.00', img: 'images/album/onewe-maze-maze.jpg' },
        { id: 5, name: 'NMIXX - Blue Valentine (Love Token ver.)', price: 'S/ 110.00', img: 'images/album/nmixx-bluevalentine.jpg' },
        { id: 6, name: 'TWS - Play Hard (Compact ver.)', price: 'S/ 90.00', img: 'images/album/tws-playhard-compact.jpg' },
        { id: 7, name: 'TWS - Play Hard (Weverse ver.)', price: 'S/ 75.00', img: 'images/album/tws-playhard-weverse.jpg' },
        { id: 8, name: 'HITGS - Things We Love : I (Standard ver.)', price: 'S/ 55.00', img: 'images/album/hitgs-thingswelove1.jpg' },
        { id: 9, name: 'HITGS - Things We Love : I (POCA ver.)', price: 'S/ 45.00', img: 'images/album/hitgs-thingswelove-poca.jpg' },
        { id: 10, name: 'BABYMONSTER - WE GO UP (Pattern ver.)', price: 'S/ 110.00', img: 'images/album/babymonster-wegoup-pattern.jpg' },
        { id: 11, name: 'BABYMONSTER - WE GO UP (Keyring ver.)', price: 'S/ 90.00', img: 'images/album/babymonster-wegoup-key.jpg'},
        { id: 12, name: 'ITZY - COLLECTOR (Japanese Album Standard ver.)', price: 'S/ 120.00', img: 'images/album/itzy-collector-jp-standard.jpg' },
        { id: 13, name: 'ITZY - COLLECTOR (Limited ver.)', price: 'S/ 160.00', img: 'images/album/itzy-collector-limited.jpg' },
        { id: 14, name: 'SUHO - Who Are You (Who Are You ver.)', price: 'S/ 85.00', img: 'images/album/suho-whoareyou-whoareyou.png' },
        { id: 15, name: 'SUHO - Who Are You (SMini ver.)', price: 'S/ 70.00', img: 'images/album/suho-whoareyou-smini.jpg' },
    ],

    'ofertas': [
        { id: 16, name: 'BTS - Love Yourself 結 Answer', price: 'S/ 110.00', img: 'images/album/bts-loveyourself-answer.png', sale: true },
        { id: 17, name: 'BTS - BE (Deluxe ver.)', price: 'S/ 160.00', img: 'images/album/bts-be-deluxe.jpg', sale: true },
        { id: 18, name: 'BLACKPINK - Kill This Love', price: 'S/ 110.00', img: 'images/album/blackpink-killthislove.jpg', sale: true },
        { id: 19, name: 'BLACKPINK - The Album', price: 'S/ 130.00', img: 'images/album/blackpink-thealbum.png', sale: true },
        { id: 20, name: 'TWICE - Formula of Love: O+T=<3', price: 'S/ 120.00', img: 'images/album/twice-formulaoflove.jpg', sale: true },
        { id: 21, name: 'TWICE - READY TO BE', price: 'S/ 110.00', img: 'images/album/twice-readytobe.png', sale: true },
        { id: 22, name: 'ATEEZ - ZERO : FEVER Part.2', price: 'S/ 105.00', img: 'images/album/ateez-fever2.jpg', sale: true },
        { id: 23, name: 'ATEEZ - Spin Off: From The Witness', price: 'S/ 110.00', img: 'images/album/ateez-halazia.jpg', sale: true },
        { id: 24, name: 'ITZY - CRAZY IN LOVE (Standard ver.)', price: 'S/ 115.00', img: 'images/album/itzy-crazyinlove.jpg', sale: true },
        { id: 25, name: 'ITZY - Guess Who (Day ver.)', price: 'S/ 90.00', img: 'images/album/itzy-guesswho.jpg', sale: true },
        { id: 26, name: 'BABYMONSTER - Pre-debut Album', price: 'S/ 85.00', img: 'images/album/babymonster-predebut.jpg', sale: true },
        { id: 27, name: 'BABYMONSTER - WE GO UP (Standard ver.)', price: 'S/ 90.00', img: 'images/album/babymonster-wegoup-standard.jpg', sale: true }
    ],

    'albumes': [
        { id: 28, name: 'BLACKPINK - The Album', price: 'S/ 130.00', img: 'images/album/blackpink-thealbum.png' },
        { id: 29, name: 'BLACKPINK - Born Pink', price: 'S/ 120.00', img: 'images/album/blackpink-bornpink.jpg' },
        { id: 30, name: 'JENNIE - Ruby', price: 'S/ 150.00', img: 'images/album/jennie-ruby.jpg' },
        { id: 31, name: 'BTS - Proof Standard ver.', price: 'S/ 460.00', img: 'images/album/bts-standard.png' },
        { id: 32, name: 'BTS - Proof Compact ver.', price: 'S/ 100.00', img: 'images/album/bts-compact.png' },
        { id: 33, name: 'BTS - Love Yourself 結 Answer', price: 'S/ 150.00', img: 'images/album/bts-loveyourself-answer.png' },
        { id: 34, name: 'BTS - Map of the Soul: 7', price: 'S/ 180.00', img: 'images/album/bts-map7.png' },
        { id: 35, name: 'TWICE - READY TO BE', price: 'S/ 110.00', img: 'images/album/twice-readytobe.png' },
        { id: 36, name: 'TWICE - Between 1&2', price: 'S/ 125.00', img: 'images/album/twice-between.jpg' },
        { id: 37, name: 'CHAEYOUNG - Lil Fantasy Vol.1', price: 'S/ 130.00', img: 'images/album/chaeyoung.jpg' },
        { id: 38, name: 'IVE - I`VE MINE', price: 'S/ 140.00', img: 'images/album/ive-mine.jpg' },
        { id: 39, name: 'IVE - IVE SECRET', price: 'S/ 120.00', img: 'images/album/ive-secret.jpg' },
        { id: 40, name: 'IVE - ELEVEN (Debut Single)', price: 'S/ 90.00', img: 'images/album/ive-eleven.jpg' },
        { id: 41, name: 'NCT 127 - 2 Baddies', price: 'S/ 130.00', img: 'images/album/nct-2bad.jpg' },
        { id: 42, name: 'NCT 127 - Fact Check', price: 'S/ 140.00', img: 'images/album/nct-factcheck.jpg' },
        { id: 43, name: 'NCT 127 - Sticker', price: 'S/ 135.00', img: 'images/album/nct-sticker.jpg' },
        { id: 44, name: 'NewJeans - Get Up', price: 'S/ 110.00', img: 'images/album/newjeans-getup.jpg' },
        { id: 45, name: 'NewJeans - OMG (Single Album)', price: 'S/ 95.00', img: 'images/album/newjeans-omg.jpg' },
        { id: 46, name: 'NewJeans - New Jeans (Debut EP)', price: 'S/ 100.00', img: 'images/album/newjeans-debut.jpg' },
        { id: 47, name: 'ATEEZ - THE WORLD EP.FIN : WILL', price: 'S/ 160.00', img: 'images/album/ateez-fin.jpg' },
        { id: 48, name: 'ATEEZ - ZERO : FEVER Part.2', price: 'S/ 105.00', img: 'images/album/ateez-fever2.jpg' },
        { id: 49, name: 'ATEEZ - Treasure EP.Fin : All To Action', price: 'S/ 120.00', img: 'images/album/ateez-treasure.jpg' },
        { id: 50, name: 'TXT - The Name Chapter: FREEFALL', price: 'S/ 155.00', img: 'images/album/txt-freefall.jpg' },
        { id: 51, name: 'TXT - Minisode 2: Thursday’s Child', price: 'S/ 125.00', img: 'images/album/txt-thursday.jpg' },
        { id: 52, name: 'TXT - The Dream Chapter: STAR', price: 'S/ 95.00', img: 'images/album/txt-star.jpg' },
        { id: 53, name: 'LE SSERAFIM - UNFORGIVEN', price: 'S/ 125.00', img: 'images/album/lesserafim-unforgiven.jpg' },
        { id: 54, name: 'LE SSERAFIM - EASY', price: 'S/ 130.00', img: 'images/album/lesserafim-easy.jpg' },
        { id: 55, name: 'LE SSERAFIM - FEARLESS (Debut)', price: 'S/ 100.00', img: 'images/album/lesserafim-fearless.jpg' },
        { id: 56, name: 'ENHYPEN - DARK BLOOD', price: 'S/ 145.00', img: 'images/album/enhypen-dark.jpg' },
        { id: 57, name: 'ENHYPEN - ORANGE BLOOD', price: 'S/ 135.00', img: 'images/album/enhypen-orange.jpg' },
        { id: 58, name: 'ENHYPEN - DIMENSION : DILEMMA', price: 'S/ 125.00', img: 'images/album/enhypen-dilemma.jpg' },
    ],

    'merch-oficial': [
        { id: 59, name: 'Lightstick Oficial BTS - ARMY Bomb Ver.4', price: 'S/ 250.00', img: 'images/merch/lightstick-bts.jpg' },
        { id: 60, name: 'Lightstick Oficial BLACKPINK', price: 'S/ 240.00', img: 'images/merch/lightstick-blackpink.jpg' },
        { id: 61, name: 'Lightstick Oficial TWICE - Candybong ∞', price: 'S/ 230.00', img: 'images/merch/lightstick-twice.png' },
        { id: 62, name: 'Lightstick Oficial SEVENTEEN - Carat Bong Ver.3', price: 'S/ 245.00', img: 'images/merch/lightstick-svt.jpg' },
        { id: 63, name: 'Lightstick Oficial ATEEZ', price: 'S/ 235.00', img: 'images/merch/lightstick-ateez.jpg' },
        { id: 64, name: 'TWICE - Nayeon Photobook Special', price: 'S/ 150.00', img: 'images/merch/twice-nayeon-photobook.png' },
        { id: 65, name: 'TWICE - Sana Photobook Special', price: 'S/ 150.00', img: 'images/merch/twice-sana-photobook.jpg' },
        { id: 66, name: 'BTS - Season’s Greetings 2022', price: 'S/ 320.00', img: 'images/merch/bts-sg2022.jpg' },
        { id: 67, name: 'Stray Kids - Season’s Greetings 2024', price: 'S/ 310.00', img: 'images/merch/skz-sg2024.jpg' },
        { id: 68, name: 'LE SSERAFIM - Season’s Greetings 2025', price: 'S/ 330.00', img: 'images/merch/lesserafim-sg2025.jpg' },
        { id: 69, name: 'Crybaby - Powerpuff Girls', price: 'S/ 180.00', img: 'images/merch/crybaby-pg.png' },
        { id: 70, name: 'Crybaby - Crying Again', price: 'S/ 190.00', img: 'images/merch/crybaby-ca.png' },
        { id: 71, name: 'Labubu - Big Into Energy', price: 'S/ 200.00', img: 'images/merch/labubu-bie.png' },
        { id: 72, name: 'Labubu - Coca Cola', price: 'S/ 210.00', img: 'images/merch/labubu-cc.jpg' },
    ],

    'merch-fan': [
        { id: 73, name: 'Lomo Cards BTS (Set de 55)', price: 'S/ 30.00', img: 'images/fanmerch/lomo-bts.jpg' },
        { id: 74, name: 'Lomo Cards BLACKPINK (Set de 55)', price: 'S/ 30.00', img: 'images/fanmerch/lomo-blackpink.jpg' },
        { id: 75, name: 'Lomo Cards Stray Kids (Set de 55)', price: 'S/ 30.00', img: 'images/fanmerch/lomo-skz.jpg' },
        { id: 76, name: 'Lomo Cards TWICE (Set de 55)', price: 'S/ 30.00', img: 'images/fanmerch/lomo-twice.jpg' },
        { id: 77, name: 'Lomo Cards ENHYPEN (Set de 55)', price: 'S/ 30.00', img: 'images/fanmerch/lomo-enhypen.jpg' },
    ],
};